name: Flutter Build and Upload

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
    
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        check-latest: true
    
    - name: Set JAVA_HOME
      run: echo "JAVA_HOME=$(dirname $(dirname $(readlink -f $(which java))))" >> $GITHUB_ENV
    
    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.24.5'
        
    - name: Install Dependencies    
      run: flutter pub get
    
    - name: Generate Code
      run: flutter pub run build_runner build --delete-conflicting-outputs

    - name: Build Android Binary
      run: flutter build apk
    
    - name: Sign APK
      run: |
        python3 -c 'import os, base64; open("output.jks", "wb").write(base64.b64decode(os.environ.get("SIGNING_KEY_BASE64")))'
        "$ANDROID_HOME/build-tools/34.0.0/apksigner" sign --ks output.jks -v --v2-signing-enabled true --ks-key-alias "$SIGNING_KEY_ALIAS" --ks-pass "pass:$KEY_STORE_PASSWORD" "$APK_PATH"
      env:
        SIGNING_KEY_BASE64: ${{ secrets.SIGNING_KEY }}
        SIGNING_KEY_ALIAS: ${{ secrets.SIGNING_KEY_ALIAS }}
        KEY_STORE_PASSWORD: ${{ secrets.KEY_STORE_PASSWORD }}
        APK_PATH: build/app/outputs/flutter-apk/app-release.apk
          
    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: android-app
        path: build/app/outputs/flutter-apk/app-release.apk

  release:
    if: startsWith(github.ref, 'refs/tags/24')
    needs:
      - build
    runs-on: ubuntu-latest
    steps:
    - name: Create release
      uses: softprops/action-gh-release@v2
      with:
        name: "NocoDB Mobile (Unofficial prototype) v${{ github.ref_name }}"
        files: "build/app/outputs/flutter-apk/app-release.apk"
        prerelease: ${{ contains(github.ref, 'dev') }}
