# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Flutter Build and Upload

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
    - uses: actions/checkout@v4
    
    - name: Set up Flutter
    - uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.24.5'
        
    - name: Install Dependencies    
    - run: flutter pub get
    
    - name: Generate Code
      run: flutter pub run build_runner build --delete-conflicting-outputs

    - name: Build Android Binary
      run: flutter build apk

      env:
          APK_PATH: build/app/outputs/flutter-apk/app-release.apk
          
    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: android-app
        path: build/app/outputs/flutter-apk/app-release.apk
      # Uncomment this step to verify the use of 'dart format' on each commit.
      # - name: Verify formatting
      #   run: dart format --output=none --set-exit-if-changed .

      # Consider passing '--fatal-infos' for slightly stricter analysis.
  release:
    if: startsWith(github.ref, 'refs/tags/24')
    needs:
      - build
    runs-on: ubuntu-latest
    steps:
      - name: Create release
        uses: softprops/action-gh-release@v2
        with:
          name: "NocoDB Mobile (Unofficial prototype) v${{ github.ref_name }}"
          files: "build/app/outputs/flutter-apk/app-release.apk"
          prerelease: ${{ contains(github.ref, 'dev') }}
